title: Xyz
subtitle: RISC-V, FPGA, ASIC
keywords:
  - Open Silicon
  - RISC-V
  - FPGA
  - ASIC
  - EDA
  - PDK
author: Wildan FQ
language: en
timezone: Asia/Jakarta

url: https://wildanfq.pages.dev

permalink: :year/:month/:day/:title/

pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: []

new_post_name: :title.md
default_layout: post
titlecase: false

external_link:
  enable: true
  field: site
  exclude: []

filename_case: 0
render_drafts: false
future: false
post_asset_folder: false
relative_link: false

syntax_highlighter: highlight.js

highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ""
  wrap: true
  hljs: false

prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

index_generator:
  path: ""
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map: {}
tag_map: {}

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

per_page: 10
pagination_dir: page

include: []
exclude: []
ignore: []

theme: next

deploy:
  type: ""

symbols_count_time:
  symbols: false
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."

search:
  path: search.xml
  field: post
  content: true
  format: html